<?php
/** @var \Theshreyas\CmsImage\Block\View $block */
$_ogimage = $block->getOgImageUrl();
if ($_ogimage != ""):
?>
    <!-- <meta property="og:url"             content="<?//= /* @noEscape */ $_post->getUrl() ?>" />
    <meta property="og:title"           content="<?//= /* @noEscape */ $_post->getName() ?>" /> -->
    <meta property="og:image"           content="<?=/* @noEscape */$_ogimage?>" />
    <!-- <meta property="og:image"           content="<?//= /* @noEscape */ $block->getImageUrl($_post->getImage()) ?>" /> -->
    <!-- <meta property="og:description"    content="<?//= /* @noEscape */ $_post->getShortDescription() ?>" /> -->
<?php endif;?>