<?php

/** @var Theshreyas\SystemXML\Block\Adminhtml\Form\Field\TimeSlider $block */
$element = $block->getElement();
$form = $element->getForm();
/** @var \Magento\Config\Block\System\Config\Form $parentForm */
$parentForm = $form->getParent();
$timeFrom = $parentForm->getConfigValue('advanced_config/complex_fields/delivery_time_from');;
$timeTo = $parentForm->getConfigValue('advanced_config/complex_fields/delivery_time_to');;
?>
<div id="time-range" class="field field-time_range">
    <label class="label" style="white-space: normal;">
        <?php echo __('Time Range: ');?>
        <span class="slider-time">
            <?php echo $block->minutesToTime($timeFrom);?>
        </span>
        <?php echo ' - '; ?>
        <span class="slider-time2">
            <?php echo $block->minutesToTime($timeTo);?>
        </span>
    </label>
    <div class="sliders_step1 control">
        <div id="slider-range"></div>
        <input type="hidden"
               name="<?php echo $block->getNameFrom();?>"
               value="<?php echo $timeFrom?>"
            />
        <input type="hidden"
               name="<?php echo $block->getNameTo();?>"
               value="<?php echo $timeTo?>"
            />
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        console.log("<?php echo $timeFrom?>");
            console.log("<?php echo $timeTo?>");
        $("#slider-range").slider({
            range: true,
            min: 0,
            max: 1440,
            step: 15,
            values: [<?php echo $timeFrom?>, <?php echo $timeTo?>],
            slide: function (e, ui) {
                var hours1 = Math.floor(ui.values[0] / 60);
                var minutes1 = ui.values[0] - (hours1 * 60);

                if (hours1.length == 1) hours1 = '0' + hours1;
                if (minutes1.length == 1) minutes1 = '0' + minutes1;
                if (minutes1 == 0) minutes1 = '00';
                if (hours1 >= 12) {
                    if (hours1 == 12) {
                        hours1 = hours1;
                        minutes1 = minutes1 + " PM";
                    } else {
                        hours1 = hours1 - 12;
                        minutes1 = minutes1 + " PM";
                    }
                } else {
                    hours1 = hours1;
                    minutes1 = minutes1 + " AM";
                }
                if (hours1 == 0) {
                    hours1 = 12;
                    minutes1 = minutes1;
                }


                $('.slider-time').html(hours1 + ':' + minutes1);

                var hours2 = Math.floor(ui.values[1] / 60);
                var minutes2 = ui.values[1] - (hours2 * 60);

                if (hours2.length == 1) hours2 = '0' + hours2;
                if (minutes2.length == 1) minutes2 = '0' + minutes2;
                if (minutes2 == 0) minutes2 = '00';
                if (hours2 >= 12) {
                    if (hours2 == 12) {
                        hours2 = hours2;
                        minutes2 = minutes2 + " PM";
                    } else if (hours2 == 24) {
                        hours2 = 11;
                        minutes2 = "59 PM";
                    } else {
                        hours2 = hours2 - 12;
                        minutes2 = minutes2 + " PM";
                    }
                } else {
                    hours2 = hours2;
                    minutes2 = minutes2 + " AM";
                }

                $('.slider-time2').html(hours2 + ':' + minutes2);
                $('[name="<?php echo $block->getNameFrom();?>"]').val(ui.values[0]);
                $('[name="<?php echo $block->getNameTo();?>"]').val(ui.values[1]);
            }
        });
    });
</script>
