<?php
$category_ids = $block->getData('category');
$limit = $block->getData('limit');
$limit = ($limit != '') && ((int)$limit != 0)? (int)$limit : 5;

$categories = $block->getCategories($category_ids);

if($categories->getSize() >= 1){
?>
	<div class="">
		<div class="card-v2 row mt-5 mb-5 sc-fc">
			<h3 class="col-lg-12 mb-5 text-center">Featured Categories</h3>
			<?php foreach ($categories as $category) { ?> 
				<div class="col-lg-3 col-6 mt-3 mb-2 pb-2 mt-lg-0 mb-lg-0 pb-lg-0">
					<div class="card-v2 text-center">
						<a href="/<?=$category->getUrlKey();?>">
							<div>
								<h4 class="sc-fc-h4 inherit"><?=$category->getName();?></h4>
							</div>

							<div class="mt-5 pt-5 pb-4">
								<img alt="" class="img-fluid" src="<?=$category->getImage();?>"/>
							</div>
						</a>
					</div>
				</div>
		<?php } ?>
		</div>
	</div>
<?php } ?>