<?php
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Items\Column\Name
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('catalogHelper');
$splitSku = implode('<br />', $catalogHelper->splitSku($escaper->escapeHtml($block->getSku())));
?>
<?php if ($_item = $block->getItem()): ?>
    <div id="order_item_<?= (int) $_item->getId() ?>_title"
         class="product-title">
        <?= $escaper->escapeHtml($_item->getName()) ?>
    </div>
    <div class="product-sku-block">
        <span><?= $escaper->escapeHtml(__('SKU'))?>:</span>
        <?php if ($_item->getProduct()) { ?>
            <a target="_blank" href="<?= /* @noEscape */ $_item->getProduct()->getProductUrl(); ?>"><?= /* @noEscape */ $splitSku ?></a>
        <?php } else {
            /* @noEscape */ echo $splitSku;
        }?>
    </div>

    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($block->getOrderOptions() as $_option): ?>
                <dt><?= $escaper->escapeHtml($_option['label']) ?>:</dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?= /* @noEscape */ $block->getCustomizedOptionValue($_option) ?>
                    <?php else: ?>
                        <?php $_option = $block->getFormattedOption($_option['value']); ?>
                        <?php $dots = 'dots' . uniqid(); ?>
                        <?php $id = 'id' . uniqid(); ?>
                        <?= $escaper->escapeHtml($_option['value'], ['a', 'br']) ?>
                        <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                            <span id="<?= /* @noEscape */ $dots; ?>"> ...</span>
                            <span id="<?= /* @noEscape */ $id; ?>">
                                <?= $escaper->escapeHtml($_option['remainder'], ['a']) ?>
                            </span>
                            <?php $scriptString = <<<script
                                require(['prototype'], function() {

script;
                            $scriptString .= "$('" . /* @noEscape */ $id . "').hide();" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $id . "').show();});" .
                                PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $dots .
                                "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $id .
                                "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $dots .
                                "').show();});" . PHP_EOL . "});" . PHP_EOL;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?= $escaper->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>